source "https://rubygems.org"


# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#

gem "jekyll", "~> 4.0"
gem "bundler", "> 2.0"

gem "minima", "~> 2.5"
gem 'jekyll-theme-lcsb-default', '~> 0.3.8'

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do 
  gem "jekyll-paginate-v2",
      "~> 3",
      :git => "https://github.com/LCSB-BioCore/jekyll-paginate-v2.git"

 gem "jekyll-feed", 
     "~> 0.6"

 gem 'jekyll-theme-lcsb-frozen-components', 
     '~> 0.0.2', 
     :git => "https://git-r3lab.uni.lu/core-services/jekyll-theme-lcsb-frozen-components.git", 
     :tag => "0.0.2"

end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1" if Gem.win_platform?
